version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2021-05-27T22-06-31Z
    volumes:
    - minio-data:/data
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: M1N104cC355K3y
      MINIO_SECRET_KEY: MInI053cR3tK3y
    entrypoint: >
      /bin/sh -c "
        mkdir -p /data/images;
        minio server /data;
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 3

  api:
    build:
      context: .
    depends_on:
      minio:
        condition: service_healthy
    ports:
    - "8080:8080"
    environment:
      LOG_LEVEL: debug
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: M1N104cC355K3y
      MINIO_SECRET_KEY: MInI053cR3tK3y
      MINIO_BUCKET: images

  openapi-ui:
    image: swaggerapi/swagger-ui:v3.49.0
    depends_on:
    - api
    volumes:
    - ./api/openapi.yaml:/openapi.yaml
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml

volumes:
  minio-data: